export { updateAct } from './act/actActions'
export { updateTimeSelect } from './timeSelect/timeSelectActions'
export { updateRoutes } from './routes/routesActions'
export { updateOutletCode, updateOutletCameraDetails } from './outletCode/outletCodeActions'
export { updateCompanyServices } from './outletServices/outletServicesActions'
